### PR TITLE
add pystac/pydantic definitions for ML-AOI extension

### LINKED ISSUE #9: ml-aoi extension schema page does not exists
I am truing to access the extension schema page at `https://stac-extensions.github.io/ml-aoi/v0.1.0/schema.json` But its giving me 404 error, page does not exists.
Could you please look into this.

### PR DESCRIPTION
**Pull request by fmigneault**
## TODO

- [x] update changelog
- [x] update tests & examples
  - [x] test examples against JSON schema
  - [x] add more combinations of `pystac` extensions using ML-AOI utilities
- [ ] release `v0.2.0` with `make bump VERSION=0.2.0` call once merged 
  (fixes #9)

### CODE REVIEW

**Comment by fmigneault** [comment]
@m-mohr 
The STAC Node Validator fails the `deploy` step because the URI of ML-AOI schema cannot be found, but I want to validate everything works with mocked schema locations before releasing them. We have a chicken-egg situation here. 
I would like to know your preferred approach regarding the CI for STAC extensions and resolving those missing refs issues.

**Comment by m-mohr** [comment]
That's not the case. The validator can handle this case. You need to specify the correct version numbers in package.json (search for 1.0.0 occurances and replace with 0.1.0). Generally, I'd recommend to search (and replace) the whole repo for "template" and "1.0.0" and replace it with the corresponding values that apply for this repo.

**Comment by fmigneault** [comment]
@m-mohr  
I see. And once I bump the versions with the new minor release, I simply need to update the package.json with the relevant numbers as well?

**Comment by m-mohr** [comment]
yes

**Pull request merged**
